### ISSUE TITLE
Tok new fails with panic: stat (...)settings.php: no such file or directory

### ISSUE THREAD

**Issue by moroland** [ironstar-io/tokaido#122]
**What happened**:

```
$ tok new sitename
🍚  Creating a brand new Drupal 8 site with Tokaido!
🏯  Generating a new docker-compose.tok.yml file
🚛  Initial sync completed
🎼  Using composer to generate the new Drupal project files. This might take some time
    1/5:	http://repo.packagist.org/p/provider-2018-10$f8bb73f5cfbccba15f67115f42d703e3e7239f9778667e2e5bcf66d0ba45bdb6.json
    2/5:	http://repo.packagist.org/p/provider-2019-01$7c886befec9421100bb7fa8e32f2790e5312fa1759dac65b716052bd27a7d228.json
    3/5:	http://repo.packagist.org/p/provider-2017$fb9fe76b52a92ee63c0fe4ab0376d227daf162299cb0c0fae6883a4d8f4f1a5f.json
    4/5:	http://repo.packagist.org/p/provider-latest$e8d435dc4ab49103756c706c82aae8e08232655107542b1c12105e3d7f16af56.json
    5/5:	http://repo.packagist.org/p/provider-2018-07$27c0466a50aa4c7354d00f8e615a062505947974d0ec594c7348099745cda724.json
    Finished: success: 5, skipped: 0, failure: 0, total: 5
    1/5:	http://repo.packagist.org/p/provider-2019-01$7c886befec9421100bb7fa8e32f2790e5312fa1759dac65b716052bd27a7d228.json
    2/5:	http://repo.packagist.org/p/provider-2018-07$27c0466a50aa4c7354d00f8e615a062505947974d0ec594c7348099745cda724.json
    3/5:	http://repo.packagist.org/p/provider-latest$e8d435dc4ab49103756c706c82aae8e08232655107542b1c12105e3d7f16af56.json
    4/5:	http://repo.packagist.org/p/provider-2017$fb9fe76b52a92ee63c0fe4ab0376d227daf162299cb0c0fae6883a4d8f4f1a5f.json
    5/5:	http://repo.packagist.org/p/provider-2018-10$f8bb73f5cfbccba15f67115f42d703e3e7239f9778667e2e5bcf66d0ba45bdb6.json
    Finished: success: 5, skipped: 0, failure: 0, total: 5
Installing ironstar-io/d8-template (0.4)
  - Installing ironstar-io/d8-template (0.4): Loading from cache
Created project in /tmp/composer
    1/1:	https://packages.drupal.org/8/drupal/provider-2019-1$bcbda8cc07e9d6e3da9121fce1cb7508a9f663618e10ba80caca25d10d44f04e.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)                  
Package operations: 145 installs, 0 updates, 0 removals
  - Installing cweagans/composer-patches (1.6.5): Loading from cache
  - Installing composer/installers (v1.6.0): Loading from cache
  - Installing composer/semver (1.5.0): Loading from cache
  - Installing drupal-composer/drupal-scaffold (2.6.1): Loading from cache
  - Installing symfony/polyfill-ctype (v1.11.0): Loading from cache
  - Installing symfony/yaml (v3.4.23): Loading from cache
  - Installing symfony/finder (v3.4.23): Loading from cache
  - Installing drupal/console-extend-plugin (0.9.2): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v3.4.23): Loading from cache
  - Installing symfony/phpunit-bridge (v3.4.23): Loading from cache
  - Installing symfony/css-selector (v3.4.23): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing doctrine/instantiator (1.2.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.8.1): Loading from cache
  - Installing phpunit/phpunit (6.5.14): Loading from cache
  - Installing mikey179/vfsstream (v1.6.5): Loading from cache
  - Installing ralouphie/getallheaders (2.0.5): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.5.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing jcalderonzumba/gastonjs (v1.2.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.11.0): Loading from cache
  - Installing twig/twig (v1.38.4): Loading from cache
  - Installing behat/mink (dev-master d5ee350): Cloning d5ee350c40 from cache
  - Installing jcalderonzumba/mink-phantomjs-driver (v0.3.3): Loading from cache
  - Installing squizlabs/php_codesniffer (3.4.1): Loading from cache
  - Installing drupal/coder (8.3.1): Cloning 29a25627e7 from cache
  - Installing instaclick/php-webdriver (1.4.5): Loading from cache
  - Installing behat/mink-selenium2-driver (dev-master 8684ee4): Cloning 8684ee4e63 from cache
  - Installing symfony/dom-crawler (v3.4.23): Loading from cache
  - Installing symfony/browser-kit (v4.2.4): Loading from cache
  - Installing fabpot/goutte (v3.2.3): Loading from cache
  - Installing symfony/event-dispatcher (v3.4.23): Loading from cache
  - Installing behat/mink-browserkit-driver (1.3.3): Loading from cache
  - Installing behat/mink-goutte-driver (v1.2.1): Loading from cache
  - Installing symfony/polyfill-php72 (v1.11.0): Loading from cache
  - Installing paragonie/random_compat (v2.0.18): Loading from cache
  - Installing symfony/polyfill-php70 (v1.11.0): Loading from cache
  - Installing symfony/http-foundation (v3.4.23): Loading from cache
  - Installing symfony/http-kernel (v3.4.23): Loading from cache
  - Installing asm89/stack-cors (1.2.0): Loading from cache
  - Installing zendframework/zend-diactoros (1.8.6): Loading from cache
  - Installing symfony/psr-http-message-bridge (v1.2.0): Loading from cache
  - Installing masterminds/html5 (2.6.0): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing egulias/email-validator (1.2.15): Loading from cache
  - Installing stack/builder (v1.0.5): Loading from cache
  - Installing zendframework/zend-stdlib (3.2.1): Loading from cache
  - Installing zendframework/zend-escaper (2.6.0): Loading from cache
  - Installing zendframework/zend-feed (2.12.0): Loading from cache
  - Installing easyrdf/easyrdf (0.9.1): Loading from cache
  - Installing symfony/routing (v3.4.23): Loading from cache
  - Installing symfony-cmf/routing (1.4.1): Loading from cache
  - Installing doctrine/annotations (v1.6.1): Loading from cache
  - Installing doctrine/reflection (v1.0.0): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/collections (v1.6.1): Loading from cache
  - Installing doctrine/cache (v1.8.0): Loading from cache
  - Installing doctrine/persistence (v1.1.0): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing doctrine/common (v2.10.0): Loading from cache
  - Installing brumann/polyfill-unserialize (v1.0.3): Loading from cache
  - Installing typo3/phar-stream-wrapper (v2.1.0): Loading from cache
  - Installing symfony/polyfill-iconv (v1.11.0): Loading from cache
  - Installing symfony/process (v3.4.23): Loading from cache
  - Installing symfony/translation (v3.4.23): Loading from cache
  - Installing symfony/validator (v3.4.23): Loading from cache
  - Installing symfony/serializer (v3.4.23): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v3.4.23): Loading from cache
  - Installing symfony/console (v3.4.23): Loading from cache
  - Installing symfony/class-loader (v3.4.23): Loading from cache
  - Installing drupal/core (8.6.13): Loading from cache
  - Installing jakub-onderka/php-console-color (v0.2): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.4): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing nikic/php-parser (v4.2.1): Loading from cache
  - Installing symfony/var-dumper (v4.2.4): Loading from cache
  - Installing psy/psysh (v0.9.9): Loading from cache
  - Installing webmozart/path-util (2.3.0): Loading from cache
  - Installing webflo/drupal-finder (1.1.0): Loading from cache
  - Installing symfony/filesystem (v3.4.23): Loading from cache
  - Installing symfony/config (v3.4.23): Loading from cache
  - Installing stecman/symfony-console-completion (0.9.0): Loading from cache
  - Installing drupal/console-en (1.8.0): Loading from cache
  - Installing dflydev/placeholder-resolver (v1.0.2): Loading from cache
  - Installing dflydev/dot-access-data (v1.1.0): Loading from cache
  - Installing dflydev/dot-access-configuration (v1.0.3): Loading from cache
  - Installing drupal/console-core (1.8.0): Loading from cache
  - Installing alchemy/zippy (0.4.3): Loading from cache
  - Installing drupal/console (1.8.0): Loading from cache
  - Installing drupal/devel (1.2.0): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing league/container (2.4.1): Loading from cache
  - Installing grasmash/yaml-expander (1.4.0): Loading from cache
  - Installing grasmash/expander (1.0.0): Loading from cache
  - Installing consolidation/config (1.2.1): Loading from cache
  - Installing consolidation/site-alias (3.0.0): Loading from cache
  - Installing consolidation/site-process (2.0.0): Loading from cache
  - Installing consolidation/output-formatters (3.4.1): Loading from cache
  - Installing consolidation/annotated-command (2.12.0): Loading from cache
  - Installing consolidation/log (1.1.1): Loading from cache
  - Installing consolidation/self-update (1.1.5): Loading from cache
  - Installing consolidation/robo (1.4.9): Loading from cache
  - Installing consolidation/filter-via-dot-access-data (1.0.0): Loading from cache
  - Installing chi-teck/drupal-code-generator (1.28.1): Loading from cache
  - Installing drush/drush (9.6.1): Loading from cache
  - Installing drupal/health_check (1.0.0): Loading from cache
  - Installing drupal/memcache (2.0.0): Loading from cache
  - Installing monolog/monolog (1.24.0): Loading from cache
  - Installing drupal/monolog (1.0.0): Loading from cache
  - Installing drupal/ctools (3.2.0): Loading from cache
  - Installing drupal/password_policy (3.0.0-alpha4): Loading from cache
  - Installing html2text/html2text (4.0.1): Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.12): Loading from cache
  - Installing drupal/mailsystem (4.1.0): Loading from cache
  - Installing drupal/swiftmailer (1.0.0-beta2): Loading from cache
  - Installing vlucas/phpdotenv (v2.6.1): Loading from cache
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
behat/mink suggests installing behat/mink-zombie-driver (fast and JS-enabled headless driver for any app (requires node.js))
behat/mink suggests installing dmore/chrome-mink-driver (fast and JS-enabled driver for any app (requires chromium or google chrome))
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/psr-http-message-bridge suggests installing nyholm/psr7 (For a super lightweight PSR-7/17 implementation)
zendframework/zend-feed suggests installing zendframework/zend-cache (Zend\Cache component, for optionally caching feeds between requests)
zendframework/zend-feed suggests installing zendframework/zend-db (Zend\Db component, for use with PubSubHubbub)
zendframework/zend-feed suggests installing zendframework/zend-http (Zend\Http for PubSubHubbub, and optionally for use with Zend\Feed\Reader)
zendframework/zend-feed suggests installing zendframework/zend-servicemanager (Zend\ServiceManager component, for easily extending ExtensionManager implementations)
zendframework/zend-feed suggests installing zendframework/zend-validator (Zend\Validator component, for validating email addresses used in Atom feeds and entries when using the Writer subcomponent)
easyrdf/easyrdf suggests installing ml/json-ld (~1.0)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
symfony/validator suggests installing psr/cache-implementation (For using the metadata cache.)
symfony/validator suggests installing symfony/intl
symfony/validator suggests installing symfony/property-access (For accessing properties within comparison constraints)
symfony/validator suggests installing symfony/expression-language (For using the Expression validator)
symfony/serializer suggests installing psr/cache-implementation (For using the metadata cache.)
symfony/serializer suggests installing symfony/property-info (To deserialize relations.)
symfony/serializer suggests installing symfony/property-access (For using the ObjectNormalizer.)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/console suggests installing symfony/lock
symfony/class-loader suggests installing symfony/polyfill-apcu (For using ApcClassLoader on HHVM)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
alchemy/zippy suggests installing guzzle/guzzle (To use the GuzzleTeleporter with Guzzle 3)
drupal/console suggests installing symfony/thanks (Thank your favorite PHP projects on Github using the CLI!)
consolidation/robo suggests installing pear/archive_tar (Allows tar archives to be created and extracted in taskPack and taskExtract, respectively.)
consolidation/robo suggests installing henrikbjorn/lurker (For monitoring filesystem changes in taskWatch)
consolidation/robo suggests installing patchwork/jsqueeze (For minifying JS files in taskMinify)
consolidation/robo suggests installing natxet/CssMin (For minifying CSS files in taskMinify)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
  - Downloading 1/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/sites/default/default.services.yml
  - Downloading 2/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/index.php
  - Downloading 3/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/robots.txt
  - Downloading 5/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/update.php
  - Downloading 5/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/sites/default/default.settings.php
  - Downloading 6/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/web.config
  - Downloading 7/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/.htaccess
  - Downloading 8/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/sites/example.settings.local.php
  - Downloading 9/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/sites/example.sites.php
  - Downloading 10/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/sites/development.services.yml
  - Downloading 11/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/.ht.router.php
  - Downloading 12/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/.gitattributes
  - Downloading 13/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/.editorconfig
  - Downloading 14/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/.eslintrc.json
  - Downloading 16/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/.eslintignore
  - Downloading 16/16: https://git.drupalcode.org/project/drupal/raw/8.6.13/.csslintrc
  - Downloading 1/2: https://git.drupalcode.org/project/drupal/raw/8.6.13/.editorconfig
  - Downloading 2/2: https://git.drupalcode.org/project/drupal/raw/8.6.13/.gitattributes
> DrupalProject\composer\ScriptHandler::createRequiredFiles
Create a sites/default/settings.php file with chmod 0660
Create a sites/default/files directory with chmod 0770
⠹   Waiting for sync to complete. This might take a few minutes...
🙅‍  Your new Drupal site failed to sync from the Tokaido environment to your local disk
panic: stat /folder/to/site/web/sites/default/settings.php: no such file or directory

goroutine 1 [running]:
github.com/ironstar-io/tokaido/services/tok.New(0xc00016c120, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/ironstar-io/tokaido/services/tok/new.go:121 +0x7bd
github.com/ironstar-io/tokaido/cmd.glob..func8(0x1becf80, 0xc00016c120, 0x1, 0x1)
	/go/src/github.com/ironstar-io/tokaido/cmd/new.go:19 +0x70
github.com/ironstar-io/tokaido/vendor/github.com/spf13/cobra.(*Command).execute(0x1becf80, 0xc00016c0c0, 0x1, 0x1, 0x1becf80, 0xc00016c0c0)
	/go/src/github.com/ironstar-io/tokaido/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/ironstar-io/tokaido/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1bebc80, 0x0, 0x0, 0x157049b)
	/go/src/github.com/ironstar-io/tokaido/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/ironstar-io/tokaido/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/ironstar-io/tokaido/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/go/src/github.com/ironstar-io/tokaido/main.go:10 +0x28


```

**Environment**:
- Tokaido version (use `tok version`): 
Tokaido Version: v1.7.0
Build Date:      2019-03-28T22:15:58Z
Compiler:        go1.12.1
Platform:        darwin/amd64
- Drupal version 8
- Operating system and version: MacOS Mojave 10.14.4 (18E226)

**Comment by otakumike** [comment]
Hey @moroland as we've discussed in Slack this should all be fixed now as part of the rework of `tok new` which you can now check out in the `tok-edge` release
